### ISSUE TITLE
push(), getToken()  and other http methods fail if behind a proxy

### ISSUE THREAD

**Issue by mdip** [Raudius/Pushraven#24]
It would be great to set a proxy parameter to pass it to the .openConnection() methods.

**Comment by Raudius** [comment]
It should be fairly simple to add a proxy parameter to the push method, But for the getAccessToken() method to work you will need to set the environment variables:

```
System.setProperty("https.proxyHost", "localhost");
System.setProperty("https.proxyPort", "3128");
```

Would this be an acceptable solution or can you suggest a better way perhaps?

I can also look into retrieving the Google credential manually, instead of using the google-api-client dependency.
